# docker-compose.yaml
version: "3.8"

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_final
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
